on: [push]


name: AzureTestSGCreate

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_BMGSUB_SUB_SECRET }}

    - run: |
        az deployment sub create --name demoSubDeployment --location centralus --template-uri "https://raw.githubusercontent.com/admbmg/AutomateDemo/main/TemplateTest1.json" --parameters rgName=rg_we_demo1 rgLocation=centralus